### ISSUE TITLE
建议：删掉 site-packages，使用requirements.txt

### ISSUE THREAD

**Issue by dd1994** [BeginMan/codetheme#2]
用virtualenv隔离后，新建一个 requirements.txt 文件，像这样：

``` python
Django==1.6.2
MySQL-python==1.2.4
BeautifulSoup==4.3.2
requests==1.2.3
pytz==2012d
```

里面填好第三方库和版本号即可，然后使用`pip install -r requirements.txt`即可安装所有安装包。这样比直接复制  site-packages 目录好多了，更加清晰易懂。
参考: http://sfdye.com/articles/django-best-practice-and-deployment-with-nginx-gunicorn-and-supervisor

**Comment by limboinf** [comment]
@dd1994 ok,谢谢啦

**Comment by limboinf** [comment]
@dd1994 不过有些第三方库还是要保留,毕竟SAE提供的不全,如qiniu,和自己设置的库等.
